Feature: Booking write UI

  Background:
    * configure driver = { type: 'chrome' }

  Scenario: Create, update, patch and delete a booking from the UI
    Given driver webUrl
    And waitFor('[data-testid=login-shell]')
    When click('[data-testid=login-submit]')
    Then waitFor('[data-testid=app-shell]')

    When click('[data-testid=nav-create]')
    Then waitFor('[data-testid=create-form]')
    And clear('[data-testid=create-firstname]')
    And input('[data-testid=create-firstname]', 'UiCreate')
    And clear('[data-testid=create-lastname]')
    And input('[data-testid=create-lastname]', 'Flow')
    And clear('[data-testid=create-totalprice]')
    And input('[data-testid=create-totalprice]', '222')
    And clear('[data-testid=create-checkin]')
    And input('[data-testid=create-checkin]', '2026-06-01')
    And clear('[data-testid=create-checkout]')
    And input('[data-testid=create-checkout]', '2026-06-03')
    And clear('[data-testid=create-additionalneeds]')
    And input('[data-testid=create-additionalneeds]', 'Late checkout')
    And click('[data-testid=create-submit]')
    Then waitForText('[data-testid=toast-stack]', 'Da tao booking moi')
    And waitForText('[data-testid=response-json]', 'bookingid')
    * def createdId = script("JSON.parse(document.querySelector('[data-testid=response-json]').innerText).bookingid")

    When click('[data-testid=nav-update]')
    Then waitFor('[data-testid=update-form]')
    And clear('[data-testid=update-id]')
    And input('[data-testid=update-id]', createdId)
    And clear('[data-testid=update-firstname]')
    And input('[data-testid=update-firstname]', 'UiUpdated')
    And clear('[data-testid=update-lastname]')
    And input('[data-testid=update-lastname]', 'Flow')
    And clear('[data-testid=update-totalprice]')
    And input('[data-testid=update-totalprice]', '333')
    And click('[data-testid=update-submit]')
    Then waitForText('[data-testid=toast-stack]', 'Da cap nhat toan bo booking')
    And waitForText('[data-testid=response-json]', 'UiUpdated')

    When click('[data-testid=nav-patch]')
    Then waitFor('[data-testid=patch-form]')
    And clear('[data-testid=patch-id]')
    And input('[data-testid=patch-id]', createdId)
    And clear('[data-testid=patch-firstname]')
    And input('[data-testid=patch-firstname]', 'UiPatched')
    And clear('[data-testid=patch-lastname]')
    And input('[data-testid=patch-lastname]', 'Flow')
    And clear('[data-testid=patch-totalprice]')
    And input('[data-testid=patch-totalprice]', '444')
    And click('[data-testid=patch-submit]')
    Then waitForText('[data-testid=toast-stack]', 'Da cap nhat mot phan booking')
    And waitForText('[data-testid=response-json]', 'UiPatched')

    When click('[data-testid=nav-delete]')
    Then waitFor('[data-testid=delete-form]')
    And clear('[data-testid=delete-id]')
    And input('[data-testid=delete-id]', createdId)
    And click('[data-testid=delete-submit]')
    Then waitForText('[data-testid=toast-stack]', 'Da xoa booking')
    And waitForText('[data-testid=response-json]', 'booking deleted')
